In [11]:
# Import dependencies
import pandas as pd
import numpy as np
from pprint import pprint

In [12]:
# Read the data into a Pandas DataFrame
realEstateCa_df = pd.read_csv('Resources/RealEstate_California2.csv')
realEstateCa_df.head()

,temp_index,id,stateId,countyId,cityId,country,datePostedString,is_bankOwned,is_forAuction,event,...,parking,garageSpaces,hasGarage,levels,pool,spa,isNewConstruction,hasPetsAllowed,homeType,county
0,1,95717-2087851113,9,77,24895,USA,1/13/2021,0,0,Listed for sale,...,0,0,0,0,0,0,0,0,LOT,Placer County
1,2,94564-18496265,9,189,36958,USA,7/12/2021,0,0,Listed for sale,...,1,2,1,One Story,0,0,0,0,SINGLE_FAMILY,Contra Costa County
2,3,94564-18484475,9,190,36958,USA,7/8/2021,0,0,Listed for sale,...,1,2,1,One Story,0,0,0,0,SINGLE_FAMILY,Contra Costa County
3,4,94564-18494835,9,191,36958,USA,7/7/2021,0,0,Listed for sale,...,1,1,1,Two Story,0,1,0,0,SINGLE_FAMILY,Contra Costa County
4,5,94564-2069722747,9,192,36958,USA,7/7/2021,0,0,Listed for sale,...,0,0,0,0,0,0,0,0,LOT,Contra Costa County

In [13]:
# Brief summary of the realEstateCa_df DataFrame before cleaning.
realEstateCa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35389 entries, 0 to 35388
Data columns (total 39 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   temp_index          35389 non-null  int64
 1   id                  35389 non-null  object
 2   stateId             35389 non-null  int64
 3   countyId            35389 non-null  int64
 4   cityId              35389 non-null  int64
 5   country             35389 non-null  object
 6   datePostedString    35386 non-null  object
 7   is_bankOwned        35389 non-null  int64
 8   is_forAuction       35389 non-null  int64
 9   event               35100 non-null  object
 10  time                35100 non-null  float64
 11  price               35389 non-null  int64
 12  pricePerSquareFoot  35389 non-null  int64
 13  city                35389 non-null  object
 14  state               35389 non-null  object
 15  yearBuilt           35389 non-null  int64
 16  streetAddress       35388 non-null  object
 17  zipcode             35364 non-null  float64
 18  longitude           35389 non-null  float64
 19  latitude            35389 non-null  float64
 20  hasBadGeocode       35389 non-null  int64
 21  description         35110 non-null  object
 22  currency            35389 non-null  object
 23  livingArea          35389 non-null  int64
 24  livingAreaValue     35389 non-null  float64
 25  lotAreaUnits        35389 non-null  object
 26  bathrooms           35389 non-null  int64
 27  bedrooms            35389 non-null  int64
 28  buildingArea        35389 non-null  int64
 29  parking             35389 non-null  int64
 30  garageSpaces        35389 non-null  int64
 31  hasGarage           35389 non-null  int64
 32  levels              35389 non-null  object
 33  pool                35389 non-null  int64
 34  spa                 35389 non-null  int64
 35  isNewConstruction   35389 non-null  int64
 36  hasPetsAllowed      35389 non-null  int64
 37  homeType            35389 non-null  object
 38  county              35389 non-null  object
dtypes: float64(5), int64(21), object(13)
memory usage: 10.5+ MB

In [14]:
# Get the crowdfunding_info_df columns.
print(realEstateCa_df.columns)

Index(['temp_index', 'id', 'stateId', 'countyId', 'cityId', 'country',
       'datePostedString', 'is_bankOwned', 'is_forAuction', 'event', 'time',
       'price', 'pricePerSquareFoot', 'city', 'state', 'yearBuilt',
       'streetAddress', 'zipcode', 'longitude', 'latitude', 'hasBadGeocode',
       'description', 'currency', 'livingArea', 'livingAreaValue',
       'lotAreaUnits', 'bathrooms', 'bedrooms', 'buildingArea', 'parking',
       'garageSpaces', 'hasGarage', 'levels', 'pool', 'spa',
       'isNewConstruction', 'hasPetsAllowed', 'homeType', 'county'],
      dtype='object')

In [15]:
# Get count of unique ids
unique_ids = realEstateCa_df["id"].nunique()
unique_ids

31238

In [16]:
realEstateCa_df.dropna(inplace = True)
realEstateCa_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34814 entries, 0 to 35388
Data columns (total 39 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   temp_index          34814 non-null  int64
 1   id                  34814 non-null  object
 2   stateId             34814 non-null  int64
 3   countyId            34814 non-null  int64
 4   cityId              34814 non-null  int64
 5   country             34814 non-null  object
 6   datePostedString    34814 non-null  object
 7   is_bankOwned        34814 non-null  int64
 8   is_forAuction       34814 non-null  int64
 9   event               34814 non-null  object
 10  time                34814 non-null  float64
 11  price               34814 non-null  int64
 12  pricePerSquareFoot  34814 non-null  int64
 13  city                34814 non-null  object
 14  state               34814 non-null  object
 15  yearBuilt           34814 non-null  int64
 16  streetAddress       34814 non-null  object
 17  zipcode             34814 non-null  float64
 18  longitude           34814 non-null  float64
 19  latitude            34814 non-null  float64
 20  hasBadGeocode       34814 non-null  int64
 21  description         34814 non-null  object
 22  currency            34814 non-null  object
 23  livingArea          34814 non-null  int64
 24  livingAreaValue     34814 non-null  float64
 25  lotAreaUnits        34814 non-null  object
 26  bathrooms           34814 non-null  int64
 27  bedrooms            34814 non-null  int64
 28  buildingArea        34814 non-null  int64
 29  parking             34814 non-null  int64
 30  garageSpaces        34814 non-null  int64
 31  hasGarage           34814 non-null  int64
 32  levels              34814 non-null  object
 33  pool                34814 non-null  int64
 34  spa                 34814 non-null  int64
 35  isNewConstruction   34814 non-null  int64
 36  hasPetsAllowed      34814 non-null  int64
 37  homeType            34814 non-null  object
 38  county              34814 non-null  object
dtypes: float64(5), int64(21), object(13)
memory usage: 10.6+ MB

In [17]:
print(realEstateCa_df.duplicated())

0        False
1        False
2        False
3        False
4        False
         ...
35384    False
35385    False
35386    False
35387    False
35388    False
Length: 34814, dtype: bool

In [18]:
# Remove homes listed for less than $1000
filter = (realEstateCa_df[realEstateCa_df["price"] >= 1000]) 

# Remove homes with less than 120 living area
filter2 = (filter[filter["livingArea"] >= 120]) 

# Remove homes with no bathrooms
filter3 = (filter2[filter2["bathrooms"] != 0]) 

filter4 = (filter3[filter3["homeType"] != "MULTI_FAMILY"])  

filter5 = (filter4[filter4["homeType"] != "LOT"])  

filter6 = (filter5[filter5["homeType"] != "MILY"])

In [19]:

filter6.to_csv("Resources/filter6.csv")

In [20]:
print(realEstateCa_df.columns)

Index(['temp_index', 'id', 'stateId', 'countyId', 'cityId', 'country',
       'datePostedString', 'is_bankOwned', 'is_forAuction', 'event', 'time',
       'price', 'pricePerSquareFoot', 'city', 'state', 'yearBuilt',
       'streetAddress', 'zipcode', 'longitude', 'latitude', 'hasBadGeocode',
       'description', 'currency', 'livingArea', 'livingAreaValue',
       'lotAreaUnits', 'bathrooms', 'bedrooms', 'buildingArea', 'parking',
       'garageSpaces', 'hasGarage', 'levels', 'pool', 'spa',
       'isNewConstruction', 'hasPetsAllowed', 'homeType', 'county'],
      dtype='object')